### ISSUE TITLE
Normal Mode as Default

### ISSUE THREAD

**Issue by kvnduff** [lubokkanev/vim-everywhere#5]
Would you be able to implement normal mode as the default (i, a, o, s, c to enter insert mode). It's a shame to realize the power of vim shortcuts but then not have the ability to utilize them system wide.

**Comment by lubokkanev** [comment]
Yes, it would be easy to change the default mode. 
Can you elaborate on why insert being the default mode removes the ability to utilize vim shortcuts system wide though? You can press `^[` to switch to normal mode system wide.

**Comment by kvnduff** [comment]
More than half of the time it seems there is a need to edit text rather than enter text. Having normal mode as the default would encourage vim mode typing. A simple 'i' or 'a' is simpler than the shortcut for entering normal mode. More than anything, thinking about how keyboard inputs would be streamlined with forced normal mode rather than traditional typing.

**Comment by lubokkanev** [comment]
By making it default, I suppose you mean that Normal mode should be the mode at startup of the program. Because that's the only default mode I think there is. From there on you decide to which mode to switch and you can remain in Normal indefinitely. There's no automatic switching to Insert more. 

So the improvement you're suggesting is to be able to skip the initial `^[` after the program startup and go directly to Normal mode? If that's it, I don't think it's that important as an improvement. 

Also, from my usage it seems that I spend the vast majority of time in Insert mode and only go to Normal mode when editing text or using some Arrow shortcuts - which doesn't happen often compared to time spent in the browser, for example. 

It wouldn't be useful for me to start in Normal mode and I expect that to be true for most people, so I don't want to release it like that. If you find it more useful for you, this is how to achieve it:

Replace the first line of the file `src/vim-everywhere.ahk`, saying `switchToInsertMode()` with `switchToNormalMode()`.

**Comment by kvnduff** [comment]
I understand, very reasonable.

BTW, noticed, that replacing switchToInsertMode() with switchToNormalMode() results in a call to nonexistent function. Did you mean switchToCommandMode()?

**Comment by lubokkanev** [comment]
Yeah, I updated the names recently. 
Thanks for your interest BTW :)
